<<<<<<< HEAD
var/global/list/item_tf_spawnpoints = list() // Global variable tracking which items are item tf spawnpoints

//stuff that only synths can eat
var/global/list/edible_tech = list(/obj/item/cell,
				/obj/item/circuitboard,
				/obj/item/integrated_circuit,
				/obj/item/broken_device,
				/obj/item/brokenbug,
				)

var/global/list/item_digestion_blacklist = list(
		/obj/item/hand_tele,
		/obj/item/card/id,
		/obj/item/gun,
		/obj/item/pinpointer,
		/obj/item/clothing/shoes/magboots,
		/obj/item/areaeditor/blueprints,
		/obj/item/disk/nuclear,
		/obj/item/perfect_tele_beacon,
		/obj/item/organ/internal/brain/slime,
		/obj/item/mmi/digital/posibrain,
		/obj/item/mmi/digital/robot,
		/obj/item/rig/protean)

// Options for transforming into a different mob in virtual reality.
var/global/list/vr_mob_tf_options = list(
	"Borg" = /mob/living/silicon/robot,
	"Cortical borer" = /mob/living/simple_mob/animal/borer/non_antag,
	"Hyena" = /mob/living/simple_mob/animal/hyena,
	"Giant spider" = /mob/living/simple_mob/animal/giant_spider/thermic,
	"Armadillo" = /mob/living/simple_mob/animal/passive/armadillo,
	"Parrot" = /mob/living/simple_mob/animal/passive/bird/parrot,
	"Cat" = /mob/living/simple_mob/animal/passive/cat,
	"Corgi" = /mob/living/simple_mob/animal/passive/dog/corgi,
	"Squirrel" = /mob/living/simple_mob/vore/squirrel,
	"Frog" = /mob/living/simple_mob/vore/aggressive/frog,
	"Seagull" =/mob/living/simple_mob/vore/seagull,
	"Fox" = /mob/living/simple_mob/animal/passive/fox,
	"Racoon" = /mob/living/simple_mob/animal/passive/raccoon_ch,
	"Shantak" = /mob/living/simple_mob/animal/sif/shantak,
	"Goose" = /mob/living/simple_mob/animal/space/goose,
	"Space shark" = /mob/living/simple_mob/animal/space/shark,
	"Synx" = /mob/living/simple_mob/animal/synx,
	"Dire wolf" = /mob/living/simple_mob/vore/wolf/direwolf,
	"Construct Artificer" = /mob/living/simple_mob/construct/artificer,
	"Tech golem" = /mob/living/simple_mob/mechanical/technomancer_golem,
	"Metroid" = /mob/living/simple_mob/metroid/juvenile/baby,
	"Otie" = /mob/living/simple_mob/vore/otie/cotie/chubby,
	"Red-eyed Shadekin" = /mob/living/simple_mob/shadekin/red,
	"Blue-eyed Shadekin" = /mob/living/simple_mob/shadekin/blue,
	"Purple-eyed Shadekin" = /mob/living/simple_mob/shadekin/purple,
	"Green-eyed Shadekin" = /mob/living/simple_mob/shadekin/green,
	"Yellow-eyed Shadekin" = /mob/living/simple_mob/shadekin/yellow,
	"Slime" = /mob/living/simple_mob/slime/xenobio/metal,
	"Corrupt hound" = /mob/living/simple_mob/vore/aggressive/corrupthound,
	"Deathclaw" = /mob/living/simple_mob/vore/aggressive/deathclaw/den,
	"Weretiger" = /mob/living/simple_mob/vore/weretiger,
	"Mimic" = /mob/living/simple_mob/vore/aggressive/mimic/floor/plating,
	"Giant rat" = /mob/living/simple_mob/vore/aggressive/rat,
	"Catslug" = /mob/living/simple_mob/vore/alienanimals/catslug,
	"Dust jumper" = /mob/living/simple_mob/vore/alienanimals/dustjumper,
	"Space ghost" = /mob/living/simple_mob/vore/alienanimals/spooky_ghost,
	"Teppi" = /mob/living/simple_mob/vore/alienanimals/teppi,
	"Bee" = /mob/living/simple_mob/vore/bee,
	"Dragon" = /mob/living/simple_mob/vore/bigdragon/friendly,
	"Riftwalker" = /mob/living/simple_mob/vore/demon/wendigo,
	"Horse" = /mob/living/simple_mob/vore/horse/big,
	"Morph" = /mob/living/simple_mob/vore/morph,
	"Leopardmander" = /mob/living/simple_mob/vore/leopardmander,
	"Rabbit" = /mob/living/simple_mob/vore/rabbit,
	"Red panda" = /mob/living/simple_mob/vore/redpanda,
	"Sect drone" = /mob/living/simple_mob/vore/sect_drone,
	"Armalis vox" = /mob/living/simple_mob/vox/armalis,
	"Xeno hunter" = /mob/living/simple_mob/xeno_ch/hunter,
	"Xeno queen" = /mob/living/simple_mob/xeno_ch/queen/maid,
	"Xeno sentinel" = /mob/living/simple_mob/xeno_ch/sentinel,
	"Space carp" = /mob/living/simple_mob/animal/space/carp,
	"Jelly blob" = /mob/living/simple_mob/vore/jelly,
	"SWOOPIE XL" = /mob/living/simple_mob/vore/aggressive/corrupthound/swoopie,
	"Abyss lurker" = /mob/living/simple_mob/vore/vore_hostile/abyss_lurker,
	"Abyss leaper" = /mob/living/simple_mob/vore/vore_hostile/leaper,
	"Gelatinous cube" = /mob/living/simple_mob/vore/vore_hostile/gelatinous_cube,
	"Gryphon" = /mob/living/simple_mob/vore/gryphon
	)

var/global/list/vr_mob_spawner_options = list(
	"Parrot" = /mob/living/simple_mob/animal/passive/bird/parrot,
	"Rabbit" = /mob/living/simple_mob/vore/rabbit,
	"Cat" = /mob/living/simple_mob/animal/passive/cat,
	"Fox" = /mob/living/simple_mob/animal/passive/fox,
	"Cow" = /mob/living/simple_mob/animal/passive/cow,
	"Dog" = /mob/living/simple_mob/vore/woof,
	"Horse" = /mob/living/simple_mob/vore/horse/big,
	"Hippo" = /mob/living/simple_mob/vore/hippo,
	"Sheep" = /mob/living/simple_mob/vore/sheep,
	"Squirrel" = /mob/living/simple_mob/vore/squirrel,
	"Red panda" = /mob/living/simple_mob/vore/redpanda,
	"Fennec" = /mob/living/simple_mob/vore/fennec,
	"Seagull" =/mob/living/simple_mob/vore/seagull,
	"Corgi" = /mob/living/simple_mob/animal/passive/dog/corgi,
	"Armadillo" = /mob/living/simple_mob/animal/passive/armadillo,
	"Racoon" = /mob/living/simple_mob/animal/passive/raccoon_ch,
	"Goose" = /mob/living/simple_mob/animal/space/goose,
	"Frog" = /mob/living/simple_mob/vore/aggressive/frog,
	"Dust jumper" = /mob/living/simple_mob/vore/alienanimals/dustjumper,
	"Dire wolf" = /mob/living/simple_mob/vore/wolf/direwolf,
	"Space bumblebee" = /mob/living/simple_mob/vore/bee,
	"Space bear" = /mob/living/simple_mob/animal/space/bear,
	"Otie" = /mob/living/simple_mob/vore/otie,
	"Mutated otie" =/mob/living/simple_mob/vore/otie/feral,
	"Red otie" = /mob/living/simple_mob/vore/otie/red,
	"Giant rat" = /mob/living/simple_mob/vore/aggressive/rat,
	"Giant snake" = /mob/living/simple_mob/vore/aggressive/giant_snake,
	"Hyena" = /mob/living/simple_mob/animal/hyena,
	"Space shark" = /mob/living/simple_mob/animal/space/shark,
	"Shantak" = /mob/living/simple_mob/animal/sif/shantak,
	"Kururak" = /mob/living/simple_mob/animal/sif/kururak,
	"Teppi" = /mob/living/simple_mob/vore/alienanimals/teppi,
	"Slug" = /mob/living/simple_mob/vore/slug,
	"Catslug" = /mob/living/simple_mob/vore/alienanimals/catslug,
	"Weretiger" = /mob/living/simple_mob/vore/weretiger,
	"Dust jumper" = /mob/living/simple_mob/vore/alienanimals/dustjumper,
	"Star treader" = /mob/living/simple_mob/vore/alienanimals/startreader,
	"Space ghost" = /mob/living/simple_mob/vore/alienanimals/spooky_ghost,
	"Space carp" = /mob/living/simple_mob/animal/space/carp,
	"Space jelly fish" = /mob/living/simple_mob/vore/alienanimals/space_jellyfish,
	"Abyss lurker" = /mob/living/simple_mob/vore/vore_hostile/abyss_lurker,
	"Abyss leaper" = /mob/living/simple_mob/vore/vore_hostile/leaper,
	"Gelatinous cube" = /mob/living/simple_mob/vore/vore_hostile/gelatinous_cube,
	"Panther" = /mob/living/simple_mob/vore/aggressive/panther,
	"Lizard man" = /mob/living/simple_mob/vore/aggressive/lizardman,
	"Pakkun" = /mob/living/simple_mob/vore/pakkun,
	"Synx" = /mob/living/simple_mob/animal/synx,
	"Jelly blob" = /mob/living/simple_mob/vore/jelly,
	"Voracious lizard" = /mob/living/simple_mob/vore/aggressive/dino,
	"Baby metroid" = /mob/living/simple_mob/metroid/juvenile/baby,
	"Super metroid" = /mob/living/simple_mob/metroid/juvenile/super,
	"Alpha metroid" = /mob/living/simple_mob/metroid/juvenile/alpha,
	"Gamma metroid" = /mob/living/simple_mob/metroid/juvenile/gamma,
	"Zeta metroid" = /mob/living/simple_mob/metroid/juvenile/zeta,
	"Omega metroid" = /mob/living/simple_mob/metroid/juvenile/omega,
	"Queen metroid" = /mob/living/simple_mob/metroid/juvenile/queen,
	"Xeno hunter" = /mob/living/simple_mob/animal/space/alien,
	"Xeno sentinel" = /mob/living/simple_mob/animal/space/alien/sentinel,
	"Xeno Praetorian" = /mob/living/simple_mob/animal/space/alien/sentinel/praetorian,
	"Xeno queen" = /mob/living/simple_mob/animal/space/alien/queen,
	"Xeno Empress" = /mob/living/simple_mob/animal/space/alien/queen/empress,
	"Xeno Queen Mother" = /mob/living/simple_mob/animal/space/alien/queen/empress/mother,
	"Defanged xeno" = /mob/living/simple_mob/vore/xeno_defanged,
	"Sect drone" = /mob/living/simple_mob/vore/sect_drone,
	"Sect queen" = /mob/living/simple_mob/vore/sect_queen,
	"Deathclaw" = /mob/living/simple_mob/vore/aggressive/deathclaw,
	"Great White Wolf" = /mob/living/simple_mob/vore/greatwolf,
	"Great Black Wolf" = /mob/living/simple_mob/vore/greatwolf/black,
	"Solar grub" = /mob/living/simple_mob/vore/solargrub,
	"Pitcher plant" = /mob/living/simple_mob/vore/pitcher_plant,
	"Red gummy kobold" = /mob/living/simple_mob/vore/candy/redcabold,
	"Blue gummy kobold" = /mob/living/simple_mob/vore/candy/bluecabold,
	"Yellow gummy kobold" = /mob/living/simple_mob/vore/candy/yellowcabold,
	"Marshmellow serpent" = /mob/living/simple_mob/vore/candy/marshmellowserpent,
	"Riftwalker" = /mob/living/simple_mob/vore/demon,
	"Wendigo" = /mob/living/simple_mob/vore/demon/wendigo,
	"Shadekin" = /mob/living/simple_mob/shadekin,
	"Catgirl" = /mob/living/simple_mob/vore/catgirl,
	"Wolfgirl" = /mob/living/simple_mob/vore/wolfgirl,
	"Wolftaur" = /mob/living/simple_mob/vore/wolftaur,
	"Lamia" = /mob/living/simple_mob/vore/lamia,
	"Corrupt hound" = /mob/living/simple_mob/vore/aggressive/corrupthound,
	"Corrupt corrupt hound" = /mob/living/simple_mob/vore/aggressive/corrupthound/prettyboi,
	"SWOOPIE XL" = /mob/living/simple_mob/vore/aggressive/corrupthound/swoopie,
	"Cultist Teshari" = /mob/living/simple_mob/humanoid/cultist/tesh,
	"Burning Mage" = /mob/living/simple_mob/humanoid/cultist/human/bloodjaunt/fireball,
	"Converted" = /mob/living/simple_mob/humanoid/cultist/noodle,
	"Cultist Teshari Mage" = /mob/living/simple_mob/humanoid/cultist/castertesh,
	"Monkey" = /mob/living/carbon/human/monkey,
	"Wolpin" = /mob/living/carbon/human/wolpin,
	"Sparra" = /mob/living/carbon/human/sparram,
	"Saru" = /mob/living/carbon/human/sergallingm,
	"Sobaka" = /mob/living/carbon/human/sharkm,
	"Farwa" = /mob/living/carbon/human/farwa,
	"Neaera" = /mob/living/carbon/human/neaera,
	"Stok" = /mob/living/carbon/human/stok,
	//"Gryphon" = /mob/living/simple_mob/vore/gryphon // Disabled until tested
	)
=======
GLOBAL_LIST_INIT(maint_mob_pred_options, list(
	"Rabbit" = /mob/living/simple_mob/vore/rabbit,
	"Red Panda" = /mob/living/simple_mob/vore/redpanda,
	"Fennec" = /mob/living/simple_mob/vore/fennec,
	"Fennix" = /mob/living/simple_mob/vore/fennix,
	"Fox" = /mob/living/simple_mob/animal/passive/fox,
	"Syndi-Fox" = /mob/living/simple_mob/animal/passive/fox/syndicate,
	"Raccoon" = /mob/living/simple_mob/animal/passive/raccoon_ch,
	"Cat" = /mob/living/simple_mob/animal/passive/cat,
	"Space Bumblebee" = /mob/living/simple_mob/vore/bee,
	"Space Bear" = /mob/living/simple_mob/animal/space/bear,
	"Voracious Lizard" = /mob/living/simple_mob/vore/aggressive/dino,
	"Lizardman" = /mob/living/simple_mob/vore/aggressive/lizardman,
	"Giant Frog" = /mob/living/simple_mob/vore/aggressive/frog,
	"Giant Rat" = /mob/living/simple_mob/vore/aggressive/rat,
	"Giant Lab Rat" = /mob/living/simple_mob/vore/aggressive/rat/labrat,
	"Jelly Blob" = /mob/living/simple_mob/vore/jelly,
	"Wolf" = /mob/living/simple_mob/vore/wolf,
	"Dire Wolf" = /mob/living/simple_mob/vore/wolf/direwolf,
	"Large Dog" = /mob/living/simple_mob/vore/wolf/direwolf/dog,
	"Hyena" = /mob/living/simple_mob/animal/hyena,
	"Juvenile Solargrub" = /mob/living/simple_mob/vore/solargrub,
	"Sect Queen" = /mob/living/simple_mob/vore/sect_queen,
	"Sect Drone" = /mob/living/simple_mob/vore/sect_drone,
	"Defanged Xenomorph" = /mob/living/simple_mob/vore/xeno_defanged,
	"Xenomorph Hunter" = /mob/living/simple_mob/xeno_ch/hunter,
	"Xenomorph Sentinel" = /mob/living/simple_mob/xeno_ch/sentinel,
	"Xenomorph Queen" = /mob/living/simple_mob/xeno_ch/queen,
	"Xenomorph Maid Queen" = /mob/living/simple_mob/xeno_ch/queen/maid, //We have to.
	"Panther" = /mob/living/simple_mob/vore/aggressive/panther,
	"Giant Snake" = /mob/living/simple_mob/vore/aggressive/giant_snake,
	"Deathclaw" = /mob/living/simple_mob/vore/aggressive/deathclaw,
	"Otie" = /mob/living/simple_mob/vore/otie,
	"Chubby Otie" = /mob/living/simple_mob/vore/otie/friendly/chubby,
	"Mutated Otie" = /mob/living/simple_mob/vore/otie/feral,
	"Chubby Mutated Otie" = /mob/living/simple_mob/vore/otie/feral/chubby,
	"Red Otie" = /mob/living/simple_mob/vore/otie/red,
	"Chubby Red Otie" = /mob/living/simple_mob/vore/otie/red/chubby,
	"Zorgoia" = /mob/living/simple_mob/vore/zorgoia,
	"Corrupt Hound" = /mob/living/simple_mob/vore/aggressive/corrupthound,
	"Corrupt Corrupt Hound" = /mob/living/simple_mob/vore/aggressive/corrupthound/prettyboi,
	"Corrupt JaniHound" = /mob/living/simple_mob/vore/retaliate/corrupthound/janihound,
	"Corrupt Old JaniHound" = /mob/living/simple_mob/vore/retaliate/corrupthound/janihound/old,
	"Corrupt MediHound" = /mob/living/simple_mob/vore/retaliate/corrupthound/janihound/medihound,
	"Hunter Giant Spider" = /mob/living/simple_mob/animal/giant_spider/hunter,
	"Lurker Giant Spider" = /mob/living/simple_mob/animal/giant_spider/lurker,
	"Pepper Giant Spider" = /mob/living/simple_mob/animal/giant_spider/pepper,
	"Thermic Giant Spider" = /mob/living/simple_mob/animal/giant_spider/thermic,
	"Webslinger Giant Spider" = /mob/living/simple_mob/animal/giant_spider/webslinger,
	"Frost Giant Spider" = /mob/living/simple_mob/animal/giant_spider/frost,
	"Nurse Giant Spider" = /mob/living/simple_mob/animal/giant_spider/nurse/eggless,
	"Giant Spider Queen" = /mob/living/simple_mob/animal/giant_spider/nurse/queen/eggless,
	"Red Dragon" = /mob/living/simple_mob/vore/aggressive/dragon,
	"Phoron Dragon" = /mob/living/simple_mob/vore/aggressive/dragon/virgo3b,
	"Space Dragon" = /mob/living/simple_mob/vore/aggressive/dragon/space,
	"Crypt Drake" = /mob/living/simple_mob/vore/cryptdrake,
	"Gryphon" = /mob/living/simple_mob/vore/gryphon,
	"Weretiger" = /mob/living/simple_mob/vore/weretiger,
	"Lesser Large Dragon" = /mob/living/simple_mob/vore/bigdragon/friendly/maintpred,
	"Catslug" = /mob/living/simple_mob/vore/alienanimals/catslug,
	"Squirrel" = /mob/living/simple_mob/vore/squirrel/big,
	"Pakkun" =/mob/living/simple_mob/vore/pakkun,
	"Snapdragon" =/mob/living/simple_mob/vore/pakkun/snapdragon,
	"Sand pakkun" = /mob/living/simple_mob/vore/pakkun/sand,
	"Fire pakkun" = /mob/living/simple_mob/vore/pakkun/fire,
	"Amethyst pakkun" = /mob/living/simple_mob/vore/pakkun/purple,
	"Raptor" = /mob/living/simple_mob/vore/raptor,
	"Giant Bat" = /mob/living/simple_mob/vore/bat,
	"Scel (Orange)" = /mob/living/simple_mob/vore/scel/orange,
	"Scel (Blue)" = /mob/living/simple_mob/vore/scel/blue,
	"Scel (Purple)" = /mob/living/simple_mob/vore/scel/purple,
	"Scel (Red)" = /mob/living/simple_mob/vore/scel/red,
	"Scel (Green)" = /mob/living/simple_mob/vore/scel/green,
	"Cave Stalker" = /mob/living/simple_mob/vore/stalker,
	"Kelpie" = /mob/living/simple_mob/vore/horse/kelpie,
	"Scrubble" = /mob/living/simple_mob/vore/scrubble,
	"Sonadile" = /mob/living/simple_mob/vore/sonadile,
	"kururak" = /mob/living/simple_mob/animal/sif/kururak,
	"Statue of Temptation" = /mob/living/simple_mob/vore/devil,
	"Meowl" = /mob/living/simple_mob/vore/meowl,
	"Synx" = /mob/living/simple_mob/animal/synx,
	"Reindeer" = /mob/living/simple_mob/vore/reindeer,
	"Lion/Lioness" = /mob/living/simple_mob/vore/retaliate/lion,
	"Abyss Leaper" = /mob/living/simple_mob/vore/vore_hostile/leaper,
	"Abyss Lurker" = /mob/living/simple_mob/vore/vore_hostile/abyss_lurker,
	"Swoopie XL" = /mob/living/simple_mob/vore/aggressive/corrupthound/swoopie,
	"Teppie" = /datum/category_item/catalogue/fauna/teppi,
	"Frostlit Lamp" = /mob/living/simple_mob/animal/passive/gaslamp/snow
	))
>>>>>>> cc32d60595 (Maintenance Pred Additions (#11214))
