compressionLevel: 0

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard

pnpEnableEsmLoader: false

preferInteractive: true

<<<<<<< HEAD
yarnPath: .yarn/releases/yarn-4.5.1.cjs
=======
yarnPath: .yarn/releases/yarn-4.8.1.cjs
>>>>>>> f81b273417 ([MIRROR] dependency update (#10589))
