compressionLevel: 0

enableGlobalCache: false

enableScripts: false

logFilters:
  - code: YN0004
    level: discard
  - code: YN0062
    level: discard
<<<<<<< HEAD

pnpEnableEsmLoader: false
=======
  - code: YN0002
    level: discard
    pattern: css-loader@*
>>>>>>> c3b71b3d12 ([MIRROR] dependency cleanup and loader removal (#10995))

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.5.1.cjs
